src/java/jpa/entities/FabAccount.java
/*
 * Property of CLASSE
 * Cornell Laboratory for Accelerator-based ScienceS and Education
 */
package jpa.entities;

import java.io.Serializable;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 *
 * @author dab66
 */
@Entity
@Table(name = "fab_account")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "FabAccount.findAll", query = "SELECT f FROM FabAccount f"),
    @NamedQuery(name = "FabAccount.findByAccount", query = "SELECT f FROM FabAccount f WHERE f.fabAccountPK.account = :account"),
    @NamedQuery(name = "FabAccount.findByAccountAndSubAccount", query = "SELECT f FROM FabAccount f WHERE f.fabAccountPK.account = :account AND f.fabAccountPK.subAccount = :subAccount"),
    @NamedQuery(name = "FabAccount.findBySubAccount", query = "SELECT f FROM FabAccount f WHERE f.fabAccountPK.subAccount = :subAccount")})
public class FabAccount implements Serializable {

    private static final long serialVersionUID = 1L;
    @EmbeddedId
    protected FabAccountPK fabAccountPK;
    @JoinColumns({
        @JoinColumn(name = "account", referencedColumnName = "account", insertable = false, updatable = false),
        @JoinColumn(name = "sub_account", referencedColumnName = "sub_account", insertable = false, updatable = false)})
    @OneToOne(optional = false)
    private Accounts accounts;
    @JoinColumns({
        @JoinColumn(name = "nonfab_account", referencedColumnName = "account"),
        @JoinColumn(name = "nonfab_subaccount", referencedColumnName = "sub_account")})
    @ManyToOne
    private Accounts nonFab;

    public FabAccount() {
    }

    public FabAccount(FabAccountPK fabAccountPK) {
        this.fabAccountPK = fabAccountPK;
    }

    public FabAccount(String account, String subAccount) {
        this.fabAccountPK = new FabAccountPK(account, subAccount);
    }

    public FabAccountPK getFabAccountPK() {
        return fabAccountPK;
    }

    public void setFabAccountPK(FabAccountPK fabAccountPK) {
        this.fabAccountPK = fabAccountPK;
    }

    public Accounts getAccounts() {
        return accounts;
    }

    public void setAccounts(Accounts accounts) {
        this.accounts = accounts;
    }

    public Accounts getNonFab() {
        return nonFab;
    }

    public void setNonFab(Accounts nonFab) {
        this.nonFab = nonFab;
    }

    public String getNonFabAccount() {
        System.out.println("NonFabAccount = " + this.nonFab.accountsPK.getAccount());
        return this.nonFab.accountsPK.getAccount();
    }

    public String getNonFabSubAccount() {
        return this.nonFab.accountsPK.getSubAccount();
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (fabAccountPK != null ? fabAccountPK.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof FabAccount)) {
            return false;
        }
        FabAccount other = (FabAccount) object;
        if ((this.fabAccountPK == null && other.fabAccountPK != null) || (this.fabAccountPK != null && !this.fabAccountPK.equals(other.fabAccountPK))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "jpa.entities.FabAccount[ fabAccountPK=" + fabAccountPK + " ]";
    }

}

src/java/jsf/FabAccountController.java
package jsf;

import jpa.entities.FabAccount;
import jsf.util.JsfUtil;
import jsf.util.PaginationHelper;
import jpa.session.FabAccountFacade;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;


@Named("fabAccountController")
@SessionScoped
public class FabAccountController implements Serializable {


    private FabAccount current;
    private DataModel items = null;
    @EJB private jpa.session.FabAccountFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public FabAccountController() {
    }

    public FabAccount getSelected() {
        if (current == null) {
            current = new FabAccount();
            current.setFabAccountPK(new jpa.entities.FabAccountPK());
            selectedItemIndex = -1;
        }
        return current;
    }

    private FabAccountFacade getFacade() {
        return ejbFacade;
    }
    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(30) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem()+getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (FabAccount)getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new FabAccount();
        current.setFabAccountPK(new jpa.entities.FabAccountPK());
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            current.getFabAccountPK().setAccount(current.getAccounts().getAccountsPK().getAccount());
            current.getFabAccountPK().setSubAccount(current.getAccounts().getAccountsPK().getSubAccount());
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/resources/Bundle").getString("FabAccountCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/resources/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (FabAccount)getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            current.getFabAccountPK().setAccount(current.getAccounts().getAccountsPK().getAccount());
            current.getFabAccountPK().setSubAccount(current.getAccounts().getAccountsPK().getSubAccount());
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/resources/Bundle").getString("FabAccountUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/resources/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (FabAccount)getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/resources/Bundle").getString("FabAccountDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/resources/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count-1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex+1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public FabAccount getFabAccount(jpa.entities.FabAccountPK id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass=FabAccount.class)
    public static class FabAccountControllerConverter implements Converter {

        private static final String SEPARATOR = "#";
        private static final String SEPARATOR_ESCAPED = "\\#";

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            FabAccountController controller = (FabAccountController)facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "fabAccountController");
            return controller.getFabAccount(getKey(value));
        }

        jpa.entities.FabAccountPK getKey(String value) {
            jpa.entities.FabAccountPK key;
            String values[] = value.split(SEPARATOR_ESCAPED);
            key = new jpa.entities.FabAccountPK();
            key.setAccount(values[0]);
            key.setSubAccount(values[1]);
            return key;
        }

        String getStringKey(jpa.entities.FabAccountPK value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value.getAccount());
            sb.append(SEPARATOR);
            sb.append(value.getSubAccount());
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof FabAccount) {
                FabAccount o = (FabAccount) object;
                return getStringKey(o.getFabAccountPK());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: "+FabAccount.class.getName());
            }
        }

    }

}

web/fabAccount/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateFabAccountTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:commandLink action="#{fabAccountController.prepareList}" value="#{bundle.CreateFabAccountShowAllLink}" immediate="true"/>
                &nbsp;&nbsp;&nbsp;
                <h:link outcome="/index" value="#{bundle.CreateFabAccountIndexLink}"/>
                <br /><br />
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateFabAccountLabel_accounts}" for="accounts" />
                    <h:selectOneMenu id="accounts" value="#{fabAccountController.selected.accounts}" title="#{bundle.CreateFabAccountTitle_accounts}" required="true" requiredMessage="#{bundle.CreateFabAccountRequiredMessage_accounts}">
                        <f:selectItems value="#{accountsController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{bundle.CreateFabAccountLabel_nonFab}" for="nonFab" />
                    <h:selectOneMenu id="nonFab" value="#{fabAccountController.selected.nonFab}" title="#{bundle.CreateFabAccountTitle_nonFab}" >
                        <f:selectItems value="#{accountsController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <br /><br />
                <h:commandLink action="#{fabAccountController.create}" value="#{bundle.CreateFabAccountSaveLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/fabAccount/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditFabAccountTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:link outcome="View" value="#{bundle.EditFabAccountViewLink}"/>
                &nbsp;&nbsp;&nbsp;
                <h:commandLink action="#{fabAccountController.prepareList}" value="#{bundle.EditFabAccountShowAllLink}" immediate="true"/>
                &nbsp;&nbsp;&nbsp;
                <h:link outcome="/index" value="#{bundle.EditFabAccountIndexLink}" />
                <br /><br />
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditFabAccountLabel_accounts}" for="accounts" />
                    <h:selectOneMenu id="accounts" value="#{fabAccountController.selected.accounts}" title="#{bundle.EditFabAccountTitle_accounts}" required="true" requiredMessage="#{bundle.EditFabAccountRequiredMessage_accounts}">
                        <f:selectItems value="#{accountsController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{bundle.EditFabAccountLabel_nonFab}" for="nonFab" />
                    <h:selectOneMenu id="nonFab" value="#{fabAccountController.selected.nonFab}" title="#{bundle.EditFabAccountTitle_nonFab}" >
                        <f:selectItems value="#{accountsController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <br />
                <br />
                <h:commandLink action="#{fabAccountController.update}" value="#{bundle.EditFabAccountSaveLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/fabAccount/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListFabAccountTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListFabAccountEmpty}" rendered="#{fabAccountController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{fabAccountController.items.rowCount > 0}">
                    <h:outputText value="#{fabAccountController.pagination.pageFirstItem + 1}..#{fabAccountController.pagination.pageLastItem + 1}/#{fabAccountController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{fabAccountController.previous}" value="#{bundle.Previous} #{fabAccountController.pagination.pageSize}" rendered="#{fabAccountController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{fabAccountController.next}" value="#{bundle.Next} #{fabAccountController.pagination.pageSize}" rendered="#{fabAccountController.pagination.hasNextPage}"/>&nbsp;
                    &nbsp;&nbsp;&nbsp;
                    <h:commandLink action="#{fabAccountController.prepareCreate}" value="#{bundle.ListFabAccountCreateLink}"/>
                    &nbsp;&nbsp;&nbsp;
                    <h:link outcome="/index" value="#{bundle.ListFabAccountIndexLink}"/>
                    <br />
                    <br />
                    <h:dataTable value="#{fabAccountController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListFabAccountTitle_accounts}"/>
                            </f:facet>
                            <h:outputText value="#{item.accounts}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListFabAccountTitle_nonFab}"/>
                            </f:facet>
                            <h:outputText value="#{item.nonFab}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{fabAccountController.prepareView}" value="#{bundle.ListFabAccountViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{fabAccountController.prepareEdit}" value="#{bundle.ListFabAccountEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{fabAccountController.destroy}" value="#{bundle.ListFabAccountDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/fabAccount/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewFabAccountTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:commandLink action="#{fabAccountController.destroyAndView}" value="#{bundle.ViewFabAccountDestroyLink}"/>
                &nbsp;&nbsp;&nbsp;
                <h:link outcome="Edit" value="#{bundle.ViewFabAccountEditLink}"/>
                &nbsp;&nbsp;&nbsp;
                <h:commandLink action="#{fabAccountController.prepareCreate}" value="#{bundle.ViewFabAccountCreateLink}" />
                &nbsp;&nbsp;&nbsp;
                <h:commandLink action="#{fabAccountController.prepareList}" value="#{bundle.ViewFabAccountShowAllLink}"/>
                &nbsp;&nbsp;&nbsp;
                <h:link outcome="/index" value="#{bundle.ViewFabAccountIndexLink}"/>
                <br />
                <br />
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewFabAccountLabel_accounts}"/>
                    <h:outputText value="#{fabAccountController.selected.accounts}" title="#{bundle.ViewFabAccountTitle_accounts}"/>
                    <h:outputText value="#{bundle.ViewFabAccountLabel_nonFab}"/>
                    <h:outputText value="#{fabAccountController.selected.nonFab}" title="#{bundle.ViewFabAccountTitle_nonFab}"/>
                </h:panelGrid>
                

            </h:form>
        </ui:define>
    </ui:composition>

</html>